app/src/Application/Sonata/NewsBundle/Entity/Post.php
<?php

namespace App\Application\Sonata\NewsBundle\Entity;

use Sonata\NewsBundle\Entity\BasePost as BasePost;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @see https://sonata-project.org/easy-extends
 *
 * References:
 * @see http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 */
class Post extends BasePost
{
    /**
     * @var int
     */
    protected $id;

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }
}

app/src/Form/ContactType.php
<?php

namespace App\Form;

use App\Entity\Contact;
use EWZ\Bundle\RecaptchaBundle\Form\Type\EWZRecaptchaType;
use EWZ\Bundle\RecaptchaBundle\Validator\Constraints\IsTrue as RecaptchaTrue;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContactType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'FirstName',
                TextType::class,
                ['label' => 'First Name', 'attr' => ['class' => 'form-control col-md-6']]
            )
            ->add(
                'LastName',
                TextType::class,
                ['label' => 'Last Name', 'attr' => ['class' => 'form-control col-md-6']]
            )
            ->add('email', TextType::class, ['label' => 'Email', 'attr' => ['class' => 'form-control']])
            ->add('subject', TextType::class, ['label' => 'Subject', 'attr' => ['class' => 'form-control']])
            ->add('message', TextareaType::class, ['label' => 'message', 'attr' => ['class' => 'form-control']])
            ->add('recaptcha', EWZRecaptchaType::class, ['required' => true,
                'attr' => [
                    'options' => [
                        'theme' => 'light',
                        'type' => 'image',
                        'size' => 'normal',
                        'defer' => true,
                        'async' => true,
                    ],
                ],
                'mapped' => false,
                'constraints' => [
                    new RecaptchaTrue(),
                ],
            ])
            ->add('Save', SubmitType::class, ['label' => 'Send', 'attr' => ['class' => 'btn btn-primary']]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => Contact::class,
            ]
        );
    }

    public function getName()
    {
        return 'Serach';
    }
}

app/templates/bundles/SonataNewsBundle/Post/archive.html.twig
{#

/*
 * This file is part of the Sonata package.
 *
 * (c) Thomas Rabaix <thomas.rabaix@sonata-project.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

#}

{% extends 'base.html.twig' %}
{% block title %}{{ 'title_archive'|trans({}, 'SonataNewsBundle') }}{% endblock %}

{% block stylesheets %}
{% endblock %}

{% block body %}


    <div class="">
        <div class="row">
            <div class="col-sm-9">
                <div class="p-20">
                    <div class="row blog-column-wrapper">
                        {% for post in pager.getResults() %}
                            <div class="col-md-6">
                                <!-- Image Post -->

                                <div class="blog-post blog-post-column m-b-20">
                                    <div class="post-image">
                                        {% media post.image, 'wide' %}

                                        <!--<img src="assets/images/blog/1.jpg" alt="" class="img-responsive">-->

                                    </div>
                                    <div class="p-20">
                                        <div class="text-muted"><span>by <a
                                                    class="text-dark font-secondary">{{ 'archive_author'|trans({'%author%': post.author }, 'SonataNewsBundle') }}</a>,</span>
                                            <span>{{ post.publicationDateStart | format_date }} &nbsp;|&nbsp;</span><a
                                                class="text-dark font-secondary">{{ 'comments_count'|trans({'%comments_count%': post.commentsCount }, 'SonataNewsBundle') }}</a>
                                        </div>
                                        <div class="text-muted"><span><i class="fa fa-tags">Tags: </i><a
                                                    class="text-dark font-secondary">
                                            {% if post.tags|length > 1 %}
                                                <i class="icon-tags"></i>
                                             {% else %}
                                                <i class="icon-tag"></i>
                                            {% endif %}
                                                    {{ 'published_under'|transchoice(post.tags|length, {}, 'SonataNewsBundle') }}

                                                    {% for tag in post.tags %}
                                                    <a href="{{ url('sonata_news_tag', { 'tag': tag.slug } ) }}"><span
                                                            class="label label-default">{{ tag.name }}</span>
                                                        </a>{% if not loop.last %}{% endif %}
                                                    {% endfor %}
                                        </a>,</span></div>
                                        <div class="post-title">
                                            <h3>
                                                <a href="{{ url('sonata_news_view', { 'permalink': sonata_news_permalink(post) }) }}">{{ post.title }}</a>
                                            </h3>
                                        </div>
                                        <div>
                                            <p class="text-muted">
                                                {{ post.abstract }}
                                            </p>
                                        </div>
                                        <div class="text-right">
                                            <a href="{{ url('sonata_news_view', { 'permalink': sonata_news_permalink(post) }) }}"
                                               class="btn btn-success btn-sm waves-effect waves-light">Read More <i
                                                    class="mdi mdi-arrow-right m-l-5"></i></a>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        {% else %}
                            {{ 'no_post_found'|trans({}, 'SonataNewsBundle') }}
                        {% endfor %}
                    </div>
                    <!-- end row -->


                </div>
                <ul class="pager">

                    <li{% if pager.page == pager.firstPage %} class="disabled"{% endif %}><a
                            href="{{ url(route, route_parameters|merge({'page': pager.previouspage})) }}"
                            title="{{ 'link_previous_page'|trans({}, 'SonataNewsBundle') }}"><i
                                class="fa fa-angle-left"></i>&nbsp;{{ 'link_previous_page'|trans({}, 'SonataNewsBundle') }}
                        </a>
                    <li{% if pager.page == pager.lastPage %} class="disabled"{% endif %}><a
                            href="{{ url(route, route_parameters|merge({'page': pager.nextpage})) }}"
                            title="{{ 'link_next_page'|trans({}, 'SonataNewsBundle') }}">{{ 'link_next_page'|trans({}, 'SonataNewsBundle') }}
                            &nbsp;<i class="fa fa-angle-right"></i></a></li>
                </ul>
            </div> <!-- end col -->
            <div class="col-sm-3">
                <div class="p-20">

                    <!--<div class="">
                        <h4 class="text-uppercase">Search</h4>
                        <div class="border m-b-20"></div>
                        <div class="form-group search-box">
                            <input type="text" id="search-input" class="form-control" placeholder="Search here...">
                            <button type="submit" class="btn btn-search"><i class="fa fa-search"></i></button>
                        </div>
                    </div>-->

                    <div class="m-t-50">
                        <h4 class="text-uppercase">Categories</h4>
                        <div class="border m-b-20"></div>


                    </div>


                    <!--<div class="m-t-50">
                        <h4 class="text-uppercase">Newsletter</h4>
                        <div class="border m-b-20"></div>

                        <form>
                            <div class="input-group m-t-10">
                                <input type="email" id="example-input2-group2" name="example-input2-group2"
                                       class="form-control" placeholder="Email">
                                <span class="input-group-btn">
                                            <button type="button" class="btn waves-effect waves-light btn-primary">Submit</button>
                                            </span>
                            </div>
                        </form>
                    </div>-->

                </div>
            </div> <!-- end col -->
        </div>
        <!-- end row -->
    </div>
{% endblock %}

{% block javascripts %}
    <!-- isotope plugin -->
    <script src="{{ asset('assets/plugins/isotope/js/isotope.pkgd.min.js') }}"></script>
    <script type="text/javascript">
        $('.blog-column-wrapper').isotope({
            itemSelector: '.col-md-6',
            percentPosition: true,
            masonry: {
                columnWidth: '.col-md-6'
            }
        });
    </script>


{% endblock %}

app/templates/bundles/SonataNewsBundle/Post/archive.rss.twig
{#
/*
 * This file is part of the Sonata package.
 *
 * (c) Thomas Rabaix <thomas.rabaix@sonata-project.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
#}
<?xml version="1.0" ?>
<rss version="2.0">
    <channel>
        <title>{{ blog.title }}{% if tag %} : {{ tag.name }}{% endif %}</title>
        <link>{{ blog.link }}</link>
        <description>{{ blog.description }}</description>
        {% for post in pager.getResults() %}
            <item>
                <title>{{ post.title }}</title>
                <link>{{ url('sonata_news_view', { 'permalink': sonata_news_permalink(post) }, true) }}</link>
                <description><![CDATA[ {{ post.abstract }} ]]></description>
                <pubDate>{{ post.publicationDateStart | format_datetime('eee, MM LLL yyyy HH:mm:ss ZZZ', 'en') }}</pubDate>
                <guid>{{ url('sonata_news_view', { 'permalink': sonata_news_permalink(post) }, true) }}</guid>
            </item>
        {% endfor %}
    </channel>
</rss>

app/templates/bundles/SonataNewsBundle/Post/comment_form.html.twig
{#

/*
 * This file is part of the Sonata package.
 *
 * (c) Thomas Rabaix <thomas.rabaix@sonata-project.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

#}


{{ form_start(form, { attr: { class: 'contact-form', role: 'form' } }) }}
<div class="form-group">
    {{ form_widget(form) }}
</div>
<div class="form-actions">
    <button type="submit" class="btn btn-custom"><i
                class="glyphicon glyphicon-pencil"></i>&nbsp;{{ 'btn_add_comment'|trans({}, 'SonataNewsBundle') }}
    </button>
</div>
{{ form_end(form) }}

app/templates/bundles/SonataNewsBundle/Post/comments.html.twig
{#

/*
 * This file is part of the Sonata package.
 *
 * (c) Thomas Rabaix <thomas.rabaix@sonata-project.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

#}


    {% for comment in pager.results %}
        <ul class="media-list">

            <li class="media">
                <a class="pull-left" href="#">
                    <img class="media-object img-circle"
                         src="resources/images/users/avatar-2.jpg" alt="img">
                </a>
                <div class="media-body">
                    <h5 class="media-heading"><a href="{{ comment.url }}" target="new"
                                                 rel="nofollow">{{ comment.name }}</a></h5>
                    <h6 class="text-muted"> {{ comment.createdAt | format_date }}</h6>
                    <p> {{ comment.message }}</p>

                </div>
            </li>
        </ul>
    {% else %}
        <li>{{ 'no_comments_available'|trans({}, 'SonataNewsBundle') }}</li>
    {% endfor %}

app/templates/bundles/SonataNewsBundle/Post/view.html.twig
{#

/*
 * This file is part of the Sonata package.
 *
 * (c) Thomas Rabaix <thomas.rabaix@sonata-project.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

#}




{% extends 'base.html.twig' %}
{% block title %}{{ 'title_archive'|trans({}, 'SonataNewsBundle') }}{% endblock %}

{% block stylesheets %}
{% endblock %}

{% block body %}
    <div class="blog-list-wrapper">
        <div class="row">
            <div class="col-sm-9">
                <div class="p-20">
                    <div class="property-card">
                        <div class="property-content">
                            <!-- Image Post -->
                            <div class="blog-post m-b-30">
                                <div class="post-image">
                                    {% media post.image, 'wide' %}
                                    <img src="resources/images/blog/1.jpg" alt="" class="img-responsive">
                                    <span class="label label-danger">Lifestyle</span>
                                </div>
                                <div class="text-muted"><span>by <a
                                                class="text-dark font-secondary">{{ 'archive_author'|trans({'%author%': post.author }, 'SonataNewsBundle') }}&nbsp;|&nbsp;</a></span>
                                    <span>{{ post.publicationDateStart | format_date }}</span></div>
                                <div class="text-muted"><span><i class="fa fa-tags">Tags: </i><a
                                                class="text-dark font-secondary">
                                            {% if post.tags|length > 1 %}
                                                <i class="icon-tags"></i>
                                             {% else %}
                                                <i class="icon-tag"></i>
                                            {% endif %}
                                            {{ 'published_under'|transchoice(post.tags|length, {}, 'SonataNewsBundle') }}

                                            {% for tag in post.tags %}
                                            <a href="{{ url('sonata_news_tag', { 'tag': tag.slug } ) }}"><span
                                                        class="label label-default">{{ tag.name }}</span>
                                                </a>{% if not loop.last %}{% endif %}
                                            {% endfor %}
                                        </a></span></div>
                                <div class="post-title">
                                    <h3>
                                        <a href="{{ url('sonata_news_view', { 'permalink': sonata_news_permalink(post) }) }}">{{ post.title }}</a>
                                    </h3>
                                </div>

                                <div>

                                    {{ post.content|raw }}
                                </div>
                            </div>


                            <div class="m-t-50">
                                <h4 class="text-uppercase">About Author</h4>
                                <div class="border m-b-20"></div>

                                <div class="media">
                                    <div class="media-left">
                                        <a href="#"> <img class="media-object m-r-10" alt="64x64"
                                                          src="assets/images/users/avatar-1.jpg"
                                                          style="width: 96px; height: 96px;"> </a>
                                    </div>
                                    <div class="media-body">
                                        <h4 class="media-heading">Daniel Syme</h4>
                                        <p>
                                            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque
                                            ante sollicitudin commodo.
                                        </p>

                                        <a href="javascript:void(0);"
                                           class="btn btn-xs btn-success waves-light waves-effect">View Profile</a>
                                    </div>
                                </div>
                            </div>

                            <hr/>

                            <div class="m-t-50 blog-post-comment">
                                <h4 class="text-uppercase">Comments <small>(4)</small></h4>
                                <div class="border m-b-20"></div>

                                {{ render(controller('SonataNewsBundle:Post:comments', {'postId': post.id})) }}

                                <h4 class="text-uppercase m-t-50">Leave a comment</h4>
                                <div class="border m-b-20"></div>

                                {% if post.iscommentable %}
                                    {{ render(controller('Sonata\\NewsBundle\\Action\\CreateCommentFormAction', {
                                        'postId': post.id,
                                        'form': form
                                    })) }}
                                {% else %}
                                    <div>
                                        {{ 'message_comments_are_closed'|trans({}, 'SonataNewsBundle') }}
                                    </div>
                                {% endif %}


                            </div><!-- end m-t-50 -->
                        </div>
                    </div>
                </div> <!-- end p-20 -->
            </div> <!-- end col -->
            <div class="col-sm-3">
                <div class="p-20">

                    <div class="">
                        <h4 class="text-uppercase">Search</h4>
                        <div class="border m-b-20"></div>
                        <div class="form-group search-box">
                            <input type="text" id="search-input" class="form-control" placeholder="Search here...">
                            <button type="submit" class="btn btn-search"><i class="fa fa-search"></i></button>
                        </div>
                    </div>


                </div>
            </div> <!-- end col -->
        </div>
        <!-- end row -->
    </div>



{% endblock %}

        {% block javascripts %}
        {% endblock %}